package:
  name: linelisting
  version: 0.0.1

source:
  git_url: https://github.com/DiDigsDNA/linelisting
  git_rev: master

requirements:
  run:
    - python 2.7
    - biopython

build:
  number: 0

about:
  home: https://github.com/DiDigsDNA/linelisting
